apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: resolver
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: skylab00/resolver:v01
          timeoutSeconds: 600

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: resolver
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: parsed
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: resolver
  reply:
    channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: resolved
